version: '3.5'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.1.1
    hostname: kafka
    container_name: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_LISTENERS: EXTSSL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: EXTSSL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTSSL:SSL
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTSSL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_SECURITY_PROTOCOL: SSL
      # if this is not set any client will be able to bi-pass SSL authentication
      KAFKA_SSL_CLIENT_AUTH: required
      # the key in the key store must be common between the client & server
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.server.keystore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka.keystore.creds
      KAFKA_SSL_KEY_CREDENTIALS: kafka.keystore.creds
      # the server truststore will allow any client truststore signed with the same root CA to authenticate against the sever truststore
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka.truststore.creds
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: " "
      # to prevent any authenticated principle access we must enable ACLs
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      # the principle (CN name of the key) is authorised
      KAFKA_SUPER_USERS: 'User:CN=Essexboy1'
    depends_on:
      - zookeeper
    volumes:
      - ./secrets:/etc/kafka/secrets
